### PR TITLE
pg fix for OTP >= 23, pg2 was removed in OTP 24.

### PR DESCRIPTION
**Pull request by jimhansson**
This should work from OTP 23 and up, I have only tested it with OTP 25

### CODE REVIEW

**Comment by cabol** [comment]
Hey 👋 ! Overall looks good, but one of the things we would like to keep is backward compatibility, so perhaps the best way is to create a new module to encapsulate the access either to `:pg` or `:pg2`, depending on the OTP version, something like [THIS](https://github.com/cabol/shards_dist/blob/initial_impl/src/shards_dist_pg.erl). Let me know WDYT. Thanks!

**Comment by jimhansson** [comment]
I was looking into a module called uniPg that does that but was not happy
with adding new dependency out of the blue, but if you are ok with that
kind of solution then I will do it that way.


 also thinking of doing a branch for changing gen_fsm to gen_statem,  might
use -ifdef directives for that.

Den fre 25 nov. 2022 08:23Carlos Andres Bolaños R.A. <
***@***.***> skrev:

**Comment by cabol** [comment]
> I was looking into a module called uniPg that does that but was not happy
with adding new dependency out of the blue, but if you are ok with that
kind of solution then I will do it that way.

Yeah, we can add a wrapper module to the project, like the one in the example.

>  also thinking of doing a branch for changing gen_fsm to gen_statem,  might
use -ifdef directives for that.

That would be awesome!

**Comment by jimhansson** [comment]
closing this, have a new that branch that I think is better

**Pull request closed without merging**
